#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CS-B")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMeterReads(MeterReads instance);
    partial void UpdateMeterReads(MeterReads instance);
    partial void DeleteMeterReads(MeterReads instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CSB.Properties.Settings.Default.CS_BConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ReadingList_VW> ReadingList_VW
		{
			get
			{
				return this.GetTable<ReadingList_VW>();
			}
		}
		
		public System.Data.Linq.Table<MeterReads> MeterReads
		{
			get
			{
				return this.GetTable<MeterReads>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReadingList_VW")]
	public partial class ReadingList_VW
	{
		
		private int _ID;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _StreetName;
		
		private short _BuildingNumber;
		
		private System.Nullable<short> _FlatNumber;
		
		private string _PhoneNumber;
		
		private System.Nullable<int> _HotUsage;
		
		private System.Nullable<int> _ColdUsage;
		
		private System.Nullable<System.DateTime> _ReadDate;
		
		public ReadingList_VW()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="Char(16) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="Char(16) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetName", DbType="Char(32) NOT NULL", CanBeNull=false)]
		public string StreetName
		{
			get
			{
				return this._StreetName;
			}
			set
			{
				if ((this._StreetName != value))
				{
					this._StreetName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuildingNumber", DbType="SmallInt NOT NULL")]
		public short BuildingNumber
		{
			get
			{
				return this._BuildingNumber;
			}
			set
			{
				if ((this._BuildingNumber != value))
				{
					this._BuildingNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlatNumber", DbType="SmallInt")]
		public System.Nullable<short> FlatNumber
		{
			get
			{
				return this._FlatNumber;
			}
			set
			{
				if ((this._FlatNumber != value))
				{
					this._FlatNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotUsage", DbType="Int")]
		public System.Nullable<int> HotUsage
		{
			get
			{
				return this._HotUsage;
			}
			set
			{
				if ((this._HotUsage != value))
				{
					this._HotUsage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColdUsage", DbType="Int")]
		public System.Nullable<int> ColdUsage
		{
			get
			{
				return this._ColdUsage;
			}
			set
			{
				if ((this._ColdUsage != value))
				{
					this._ColdUsage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadDate", DbType="Date")]
		public System.Nullable<System.DateTime> ReadDate
		{
			get
			{
				return this._ReadDate;
			}
			set
			{
				if ((this._ReadDate != value))
				{
					this._ReadDate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MeterReads")]
	public partial class MeterReads : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MeterReadID;
		
		private System.Nullable<int> _HotUsage;
		
		private System.Nullable<int> _ColdUsage;
		
		private System.Nullable<System.DateTime> _ReadDate;
		
		private int _IDDeliveryPoint;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMeterReadIDChanging(int value);
    partial void OnMeterReadIDChanged();
    partial void OnHotUsageChanging(System.Nullable<int> value);
    partial void OnHotUsageChanged();
    partial void OnColdUsageChanging(System.Nullable<int> value);
    partial void OnColdUsageChanged();
    partial void OnReadDateChanging(System.Nullable<System.DateTime> value);
    partial void OnReadDateChanged();
    partial void OnIDDeliveryPointChanging(int value);
    partial void OnIDDeliveryPointChanged();
    #endregion
		
		public MeterReads()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterReadID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MeterReadID
		{
			get
			{
				return this._MeterReadID;
			}
			set
			{
				if ((this._MeterReadID != value))
				{
					this.OnMeterReadIDChanging(value);
					this.SendPropertyChanging();
					this._MeterReadID = value;
					this.SendPropertyChanged("MeterReadID");
					this.OnMeterReadIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotUsage", DbType="Int")]
		public System.Nullable<int> HotUsage
		{
			get
			{
				return this._HotUsage;
			}
			set
			{
				if ((this._HotUsage != value))
				{
					this.OnHotUsageChanging(value);
					this.SendPropertyChanging();
					this._HotUsage = value;
					this.SendPropertyChanged("HotUsage");
					this.OnHotUsageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColdUsage", DbType="Int")]
		public System.Nullable<int> ColdUsage
		{
			get
			{
				return this._ColdUsage;
			}
			set
			{
				if ((this._ColdUsage != value))
				{
					this.OnColdUsageChanging(value);
					this.SendPropertyChanging();
					this._ColdUsage = value;
					this.SendPropertyChanged("ColdUsage");
					this.OnColdUsageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadDate", DbType="Date")]
		public System.Nullable<System.DateTime> ReadDate
		{
			get
			{
				return this._ReadDate;
			}
			set
			{
				if ((this._ReadDate != value))
				{
					this.OnReadDateChanging(value);
					this.SendPropertyChanging();
					this._ReadDate = value;
					this.SendPropertyChanged("ReadDate");
					this.OnReadDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDeliveryPoint", DbType="Int NOT NULL")]
		public int IDDeliveryPoint
		{
			get
			{
				return this._IDDeliveryPoint;
			}
			set
			{
				if ((this._IDDeliveryPoint != value))
				{
					this.OnIDDeliveryPointChanging(value);
					this.SendPropertyChanging();
					this._IDDeliveryPoint = value;
					this.SendPropertyChanged("IDDeliveryPoint");
					this.OnIDDeliveryPointChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
